linters-settings:
  forbidigo:
    forbid:
      - .*\.Fatal.*
      - fmt\.Print.*

issues:
  exclude-rules:
    - path: _tests/settings
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
        - scopelint

linters:
  enable-all: true

  disable:
    - depguard
    - execinquery
    - exhaustive
    - exhaustruct
    - gomnd
    - ireturn
    - varnamelen
    - tagalign
    - wastedassign

run:
  timeout: 10m
  tests: false
